pipeline{
    agent any

    parameters{
        string(defaultValue:"",description:"Deployment Name ?",name:"deployment")
        choice(choices :["EU-WEST-2A","EU-WEST-28","EU-WEST-2C"],description: "What Az ?",name :"azdeploye")
        booleanPAram(defaultValue:false ,description:"CONFIRM DEPLOYMENT ?" ,name :"confirmdeployee")
    }

    stages{
        stage("Deploy"){
            steps{
                echo "String set to ${deployment} \n"
                echo "choice set to ${azdeploye} \n"
                echo "boolean set to ${confirmdeployee} \n"
            }

        }
    }
}