pipeline{
    agent any 
    stages{
        stage("Stage 1"){
            step{
                echo "this is stage 1"
            }
        }
        stage("Stage 2"){
            step{
                echo "this is stage 2"
            }
        }
        stage("Stage 3"){
            step{
                echo "this is stage 3"
            }
        }
        stage("Stage 4"){
            step{
                echo "this is stage 4"
            }
        }
        stage("Stage 5"){
            step{
                echo "this is stage 5"
            }
        }

    }
}